experiment:

  root_dir: "/home/yw699/codes/LLM-Hallu/"
  # "squad"/'svamp'/'nq'/"trivia_qa"/'trustful_qa_mc1'/'trustful_qa_mc2'
  dataset: 'trustful_mc2'
  seed: 42


  #few-shot setting
  few-shot: False
  brief_always: True

  add_tag: True
  prompt_template_path: "/home/yw699/codes/LLM-Hallu/data/prompt_templates/test2.txt"
  






  model_name: "meta-llama/Llama-2-7b-hf"
  # None/"default"
  stop_sequences: "default"
  max_new_tokens: 50
  
  
  sampling_method: "multi_sample"
  sample_count: 5
 
  metrics:
    - "accuracy"
    - "diversity"